---
language: ruby
env:
  - PUPPET_VERSION="~> 3.7.0" FUTURE_PARSER=yes
  - PUPPET_VERSION="~> 3.7.5" FUTURE_PARSER=yes
  - PUPPET_VERSION="~> 3.8.0" FUTURE_PARSER=yes
  - PUPPET_VERSION="~> 4.1.0"
  - PUPPET_VERSION="~> 4.2.0"
  - PUPPET_VERSION="~> 4.5.0"
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
script: bundle exec rake test
matrix:
  exclude:
    - rvm: 2.2
      env: PUPPET_VERSION="~> 3.7.0" FUTURE_PARSER=yes
    - rvm: 2.2
      env: PUPPET_VERSION="~> 3.7.5" FUTURE_PARSER=yes
    - rvm: 2.2
      env: PUPPET_VERSION="~> 3.8.0" FUTURE_PARSER=yes
